spring:
  datasource:
    username: root
    password: dlwjdals1*
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_mall?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# swagger 경로 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

