spring:
  profiles:
    group:
      "local": "local, jwt, oauth, s3"
    active: local
---
spring:
  config:
    activate:
      on-profile: "local"

  # swagger 경로 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    username: root
    password: dlwjdals1*
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_mall?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

server:
  port: 5000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
---
# Multipart 설정
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
# LOCAL 설정
spring:
  config:
    activate:
      on-profile: "profiles-local"
