spring:
  datasource:
    username: myadmin
    password: dlwjdals1*
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopping_mall?rewriteBatchedStatements=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
