spring:
  profiles:
    active: dev
    group:
      local: profiles-local
      dev: profiles-dev

  # swagger 경로 설정
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    username: {username}
    password: {password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: {url}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false

server:
  port: 5000

---
# AWS 설정
cloud:
  aws:
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---
# Multipart 설정
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

---
# LOCAL 설정
spring:
  config:
    activate:
      on-profile: "profiles-local"
---
# DEV 설정
cloud:
  aws:
    s3:
      bucket: my-shopping-mall
    credentials:
      access-key: {access-key}
      secret-key: {secret-key}
