name: shopping-mall-github-actions
run-name: ${{ github.actor }}의 쇼핑몰 깃허브

on: [push]

jobs:
  shopping-mall:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - run: chmod +x gradlew
      - run: ./gradlew clean build test